[build]
  publish = "build"
  command = "npm run build:netlify"

[build.environment]
  NODE_VERSION = "18.20.8"
  NODE_OPTIONS = "--openssl-legacy-provider"
  CI = "false"
  NPM_FLAGS = "--legacy-peer-deps"
  # Suppress deprecation warnings for cleaner builds
  GENERATE_SOURCEMAP = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Alternative commands if the main one fails
[context.production]
  command = "npm run build:netlify"

[context.deploy-preview]
  command = "npm run build:netlify"

[context.branch-deploy]
  command = "npm run build:netlify"

# Headers for better caching and security
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"